server:
  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/evaluateProject
    #    username: root
    #    password: root
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
      username: root
      password: root
  #      jdbc-url: jdbc:mariadb://localhost:3306/evaluateProject
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.springframework.web: trace
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: evaluationProject_log.txt
